project:
  type: book
  output-dir: ./_book
  resources: 
    - "**/*.ipynb"

lang: de-CH

book:
  title: "Unterlagen für den Informatikunterricht in der Klasse 2fP"
  author: "Jacques Mock Schindler"
  date: last-modified
  search: true
  
  chapters:
    # index.md ist nun Teil eines eigenen Parts, damit die Struktur einheitlich ist
    - part: "Start"
      chapters:
        - index.qmd
    
    - part: "Kryptologie"
      chapters:
        - files/250912/files.ipynb
        - files/250912/caesar.ipynb
        - files/250919_vigenere/vigenere.ipynb
        - files/250918_implementation/250918_python_implementation.ipynb
        - files/250926_break_vigenere/break.ipynb
        - files/251031/asymmetrie.md
        - files/251114_rsa/rsa.md

    - part: "Computernetzwerke"
      chapters:
        - files/250822/netzwerke.md
        - files/250822/tcpip.md
        - files/250822/nat.md
        - files/250822/tld.md
        - files/250829/three_way_handshake.md
        - files/250905/sockets.md

    - part: "Datenbanken"
      chapters:
        - files/250416/datenbank.md
        - files/250507/sql.md
        # Externe Links funktionieren am besten als .md Datei mit Link
        - files/250521/lernziele.md

    - part: "Datenstrukturen und Codierung"
      chapters:
        - files/250122/speicherstrukturen.md
        - files/250219/queue.md
        - files/250305/bst.ipynb
        - files/250312/binaersystem.md
        - files/250312/umrechnungen.ipynb
        - files/250312/muloe_umrechnungen.ipynb 
        - files/250319/base64.md
        - files/250326/lernziele.md

    - part: "Künstliche Intelligenz"
      chapters:
        - files/251107/soziale_medien.md
        - files/251128/ki_beispiel.md

    - part: "Anleitungen"
      chapters:
        - files/anleitungen/python.md
        - files/anleitungen/kurzanleitung_venv.md
        - files/anleitungen/jupyter.md
        - files/260109_plain_text_writing/plain_text_writing.md
        - files/260116_referenzen/referenzen.md
        - files/260116_referenzen/zotero.md

    - part: "Alte Programme"
      chapters:
        - files/archiv/fs25.md

  repo-url: https://github.com/SkriptenMk/I_fP_24-28
  repo-branch: main
  repo-actions: [edit, issue]

bibliography: files/references.bib
csl: chicago-notes-bibilography-access-dates.csl

execute:
  freeze: false

format:
  html:
    theme: cosmo
    code-copy: true
    toc: true
    code-line-numbers: true
  pdf:
    pdf-engine: lualatex
    documentclass: scrreprt
    papersize: a4
    number-sections: true
    colorlinks: true
    code-line-numbers: true
    # include-in-header: preamble.tex
    mainfont: "Libertinus Serif"
    monofont: "Libertinus Mono"
    monofont: "Consolas"