project:
  type: book
  output-dir: ../_book
  resources: 
    - "**/*.ipynb"

lang: de-CH

book:
  title: "Unterlagen für den Informatikunterricht in der Klasse 2fP"
  author: "Jacques Mock Schindler"
  date: last-modified
  search: true
  
  chapters:
    # index.md ist nun Teil eines eigenen Parts, damit die Struktur einheitlich ist
    - part: "Start"
      chapters:
        - index.md
    
    - part: "Kryptologie"
      chapters:
        - 250912/files.ipynb
        - 250912/caesar.ipynb
        - 250919_vigenere/vigenere.ipynb
        - 250918_implementation/250918_python_implementation.ipynb
        - 250926_break_vigenere/break.ipynb
        - 251031/asymmetrie.md
        - 251114_rsa/rsa.md

    - part: "Computernetzwerke"
      chapters:
        - 250822/netzwerke.md
        - 250822/tcpip.md
        - 250822/nat.md
        - 250822/tld.md
        - 250829/three_way_handshake.md
        - 250905/sockets.md

    - part: "Datenbanken"
      chapters:
        - 250416/datenbank.md
        - 250507/sql.md
        # Externe Links funktionieren am besten als .md Datei mit Link
        - 250521/lernziele.md

    - part: "Datenstrukturen und Codierung"
      chapters:
        - 250122/speicherstrukturen.md
        - 250219/queue.md
        - 250305/bst.ipynb
        - 250312/binaersystem.md
        - 250312/umrechnungen.ipynb
        - 250312/muloe_umrechnungen.ipynb 
        - 250319/base64.md
        - 250326/lernziele.md

    - part: "Künstliche Intelligenz"
      chapters:
        - 251107/soziale_medien.md
        - 251128/ki_beispiel.md

    - part: "Anleitungen"
      chapters:
        - anleitungen/python.md
        - anleitungen/kurzanleitung_venv.md
        - anleitungen/jupyter.md
        - 260109_plain_text_writing/plain_text_writing.md
        - 260116_referenzen/referenzen.md
        - 260116_referenzen/zotero.md

    - part: "Alte Programme"
      chapters:
        - archiv/fs25.md

  repo-url: https://github.com/SkriptenMk/I_fP_24-28
  repo-branch: main
  repo-actions: [edit, issue]

bibliography: references.bib
csl: chicago-notes-bibliography-access-dates.csl

execute:
  freeze: false

format:
  html:
    code-tools: 
      source: repo
    theme: cosmo
    code-copy: true
    toc: true
    code-line-numbers: true
  pdf:
    pdf-engine: lualatex
    documentclass: scrreprt
    papersize: a4
    number-sections: true
    colorlinks: true
    code-line-numbers: true
    include-in-header: preamble.tex
    mainfont: "Times New Roman"
    CJKmainfont: "Microsoft YaHei"
    monofont: "Consolas"